"use client";
import { Button } from "@/components/ui/button";
import { signIn, signOut } from "next-auth/react";

function SignIn() {
  const onClick = () => {
    signIn("github");
  };
  return (
    <button className="py-2 px-2 bg-gray-700 text-white" onClick={onClick}>
      Sign in
    </button>
  );
}

function SignOut({ children }: { children: React.ReactNode }) {
  return (
    <form
      action={() => {
        signOut();
      }}>
      <p>{children}</p>
      <button type="submit">Sign out</button>
    </form>
  );
}

export default function Hero() {
  return (
    <section className="flex items-center justify-center pt-32 pb-16 flex-col">
      <div className="max-w-5xl mx-auto text-center px-4 md:px-0">
        <h1 className="">
          <p className="text-6xl tracking-tighter text-muted-foreground/90 font-light">
            Introducing{" "}
            <span className="text-primary font-bold">snapshot.ai</span>
          </p>
        </h1>
        <h2 className="text-2xl font-medium pt-4 text-secondary-foreground">
          Appraisal summaries generated by AI
        </h2>
        <h3 className="text-muted-foreground text-2xl pt-8 w-full  mx-auto">
          Streamline your achievement reporting with Snapshot.ai, the AI
          platform that converts your monthly or quarterly accomplishments into
          concise summaries, tailored to your character count preference.
        </h3>
        <div className="pt-8">
          <Button>Get Started</Button>
        </div>
      </div>
    </section>
  );
}
