import { Button } from "@/components/ui/button";

export default function Hero() {
  return (
    <section className="flex items-center justify-center pt-32 pb-16 flex-col">
      <div className="max-w-5xl mx-auto text-center px-4 md:px-0">
        <h1 className="font-bold">
          <p className="text-6xl tracking-tighter">
            Introducing <span className="text-primary ">snapshot.ai</span>
          </p>
        </h1>
        <h2 className="text-2xl font-medium pt-4 text-black/80">
          Appraisal summaries generated by AI
        </h2>
        <h3 className="text-slate-600  pt-8 w-full md:w-4/6 mx-auto">
          Streamline your achievement reporting with Snapshot.ai, the AI
          platform that converts your monthly or quarterly accomplishments into
          concise summaries, tailored to your character count preference.
        </h3>
        <div className="pt-8">
          <Button>Get Started</Button>
        </div>
      </div>
    </section>
  );
}
